# Generated by Django 6.0.3 on 2026-03-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Breakfast', 'breakfast'), ('Lunch', 'lunch'), ('Dinner', 'dinner'), ('Dessert', 'dessert'), ('Keto', 'keto'), ('Vegan', 'vegan'), ("Valentine's Day", "valentine's Day"), ('Easter', 'easter'), ('Halloween', 'halloween'), ('Thanksgiving', 'thanksgiving'), ('Christmas', 'christmas'), ('New Years', 'new years')], max_length=20)),
                ('image', models.ImageField(upload_to='recipe/')),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
