# Generated by Django 6.0.3 on 2026-03-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_sub_category_alter_recipe_category_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Keto', 'keto'), ('Vegan', 'vegan'), ('Vegetarian', 'vegetarian'), ('Protein', 'protein'), ('Calorie Deficit', 'calorie deficit'), ('Gluten-Free', 'gluten-free'), ("Valentine's Day", "valentine's Day"), ('Easter', 'easter'), ('Halloween', 'halloween'), ('Thanksgiving', 'thanksgiving'), ('Christmas', 'christmas'), ('New Years', 'new years')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
